### ISSUE TITLE
[front-end] 'okta.oauth2.issuer' not found

### ISSUE THREAD

**Issue by albvol** [okta/samples-java-spring#58]
After starting the front-end example with the following command:
```
mvn \
  -Dokta.oauth2.issuer=https://{myOktaDomain}/oauth2/default \
  -Dokta.oauth2.client-id={client-id}
```

The maven project starts without problems but, as soon as I load http://localhost:8080/ the bash console shows the following error:
```
ERROR 88312 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Required key 'okta.oauth2.issuer' not found] 
```
with root cause

```
java.lang.IllegalStateException: Required key 'okta.oauth2.issuer' not found
```

I am using the following maven version:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 1.8.0_131, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "Mac"

Any suggestion?

**Comment by bdemers** [comment]
Hey @albvol!

Thanks for bringing this up.  The problem was missing "fork" configuration in the spring-boot-maven-plugin:
https://github.com/okta/samples-java-spring/pull/59/files#diff-a19e27ede91d7f2db76a4cf0fbec8c20R39-R41

The main goal of the "frontend" sample is to be able to quickly test the resource-server example, but in a way that is comfortable for Java developers (i.e. it doesn't require node, npm, etc).

I do want to caution you though. We have been talking about removing this example (just the frontend portion). As you probably wouldn't run a JS app this way, as there are more secure ways to host a JS application from within SpringBoot. For example, using a standard OAuth redirect: https://github.com/okta/samples-java-spring/tree/master/okta-hosted-login

If you are building a standalone frontend take a look at our other JS specific examples: https://github.com/okta?q=samples-&type=&language=


If you are using a specific frontend framework, let me know, maybe I can point you in the right direction!
